# Config for /workflows/sync-files.yml
# For more information see https://github.com/BetaHuhn/repo-file-sync-action#%EF%B8%8F-sync-configuration

# Syncs from sammcj/smcleod to sammcj/smcleod-hugo which creates https://beta.smcleod.net

sammcj/smcleod-hugo:
  - source: content/
    deleteOrphaned: true
  - source: assets/
    deleteOrphaned: true
  - source: layouts/
    deleteOrphaned: true
  - source: archetypes/
    deleteOrphaned: true
  - source: static/
    deleteOrphaned: true
  - source: data/
    deleteOrphaned: true
  - source: config.toml
  - source: config-beta.toml
  - source: .github
    deleteOrphaned: true
  - source: CNAME-beta
    dest: CNAME
